with home_games as (
    select
        season_id,
        game_id,
        "home" as game_location,
        wl_home as win_loss,
        team_abbreviation_home as team_name,
        team_abbreviation_away as opponent_name,
        fgm_home as fgm,
        fga_home as fga,
        fg_pct_home as fg_pct,
        fg3m_home as fg3m,
        fg3a_home as fg3a,
        fg3_pct_home as fg3_pct,
        ftm_home as ftm,
        fta_home as fta,
        ft_pct_home as ft_pct,
        oreb_home as oreb,
        dreb_home as dreb,
        reb_home as reb,
        ast_home as ast,
        pts_home as pts,
        fgm_away as opponent_fgm,
        fga_away as opponent_fga,
        fg_pct_away as opponent_fg_pct,
        fg3m_away as opponent_fg3m,
        fg3a_away as opponent_fg3a,
        fg3_pct_away as opponent_fg3_pct,
        ftm_away as opponent_ftm,
        fta_away as opponent_fta,
        ft_pct_away as opponent_ft_pct,
        oreb_away as opponent_oreb,
        dreb_away as opponent_dreb,
        reb_away as opponent_reb,
        ast_away as opponent_ast,
        pts_away as opponent_pts
    from {{ source("raw", "game") }}
),
away_games as (
    select
        season_id,
        game_id,
        "away" as game_location,
        wl_home as win_loss,
        team_abbreviation_away as team_name,
        team_abbreviation_home as opponent_name,
        fgm_away as fgm,
        fga_away as fga,
        fg_pct_away as fg_pct,
        fg3m_away as fg3m,
        fg3a_away as fg3a,
        fg3_pct_away as fg3_pct,
        ftm_away as ftm,
        fta_away as fta,
        ft_pct_away as ft_pct,
        oreb_away as oreb,
        dreb_away as dreb,
        reb_away as reb,
        ast_away as ast,
        pts_away as pts,
        fgm_home as opponent_fgm,
        fga_home as opponent_fga,
        fg_pct_home as opponent_fg_pct,
        fg3m_home as opponent_fg3m,
        fg3a_home as opponent_fg3a,
        fg3_pct_home as opponent_fg3_pct,
        ftm_home as opponent_ftm,
        fta_home as opponent_fta,
        ft_pct_home as opponent_ft_pct,
        oreb_home as opponent_oreb,
        dreb_home as opponent_dreb,
        reb_home as opponent_reb,
        ast_home as opponent_ast,
        pts_home as opponent_pts
    from {{ source("raw", "game") }}
)
SELECT * FROM home_games 
UNION 
SELECT * FROM away_games
WHERE YEAR(CAST(game_date AS DATE)) >= 2012